blank_issues_enabled: false
contact_links:
  - name: Private Support
    url: mailto:support@mxsrv.amethyst.live
    about: For security concerns or violations of Code of Conduct.
  - name: Community Support
    url: https://invite-to.amethyst.live/
    about: For general questions and support, use discussions or join us in our Discord.
