name: Matrix Compiler

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        host:
          # Build on Windows and Ubuntu.
          - windows-latest
          - ubuntu-latest
        node_version:
          # Support for Active LTS/Current - https://nodejs.org/en/about/releases/
          - 16
          - 17
        architecture:
          - x64
    name: Node.js ${{ matrix.architecture }} v${{ matrix.node_version }} with ${{ matrix.host }}
    steps:
      # Checkout with the .rc module.
      - name: Checkout Latest Files
        uses: actions/checkout@v2
        with:
          submodules: true
      # Initialize Node.js
      - name: Initialize Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - run: npm start build/library
      - run: npm start test
